# Developer Name: Harshitha
# Description: Discovery config for Montclair State University FAQ bot
# Contains global university sitemaps, school of computing sitemaps, indexes, sub pages & pages that are not discovered in sitemaps or api
# Date: 26 Sep 2025 

site:
  base: "https://www.montclair.edu"                     # global - used for sanity
  soc: "https://www.montclair.edu/school-of-computing"  # SoC


# Sitemap indexes to seed discovery
sitemaps:
  - "https://www.montclair.edu/wp-sitemap.xml"                         # global
  - "https://www.montclair.edu/school-of-computing/wp-sitemap.xml"     # soc
  - "https://www.montclair.edu/policies/wp-sitemap.xml"                # policy documents
  - "https://www.montclair.edu/red-hawk-central/wp-sitemap.xml"        # registrar + services
  - "https://www.montclair.edu/student-services/wp-sitemap.xml"        # student resources
  - "https://www.montclair.edu/global/wp-sitemap.xml"                  # OGE
  - "https://www.montclair.edu/graduate/wp-sitemap.xml"                # grad programs
  - "https://www.montclair.edu/combined-programs/wp-sitemap.xml"       # combined programs
  - "https://www.montclair.edu/information-technology/wp-sitemap.xml"  # IT policies
  - "https://www.montclair.edu/student-center/wp-sitemap.xml"          # student center
  - "http://catalog.montclair.edu/sitemap.xml"                         # catalogs

# CHANGE (Adaptability Enhancement):
# Auto-discovery is enabled so new, whitelisted domains can be added by finding their sitemaps
# and recording them in state/last_run.json (used on future runs).
# Cross-Site discovery controls 
discovery:
  autositemap: true                # try <domain>/sitemap(.xml) for new domains
  recheck_interval_days: 7         # how often to rediscover sitemaps
  last_run_db: "state/last_run.json"

  domain_whitelist:
    - "montclair.edu"
    - "www.montclair.edu"
    - "catalog.montclair.edu"

  # pages we’ll scan for deep links (no need to fetch whole site)
  seed_pages:
    - "https://www.montclair.edu/school-of-computing/graduate/"
    - "https://www.montclair.edu/school-of-computing/undergraduate/"
    - "http://catalog.montclair.edu/programs/"
    - "http://catalog.montclair.edu/courses/"

  # regex on URL PATH (no scheme/host/query)
  path_allowlist:
    - "^/graduate/programs-of-study/(computer-science|computational-linguistics|cybersecurity|data-science|information-technology)[^/]*/*$"
    - "^/programs/(computer-science|information-technology|data-science)[^/]*(/|$)"
    - "^/courses/(cs|csit)[a-z0-9-]*/?$"
    # Optional if you also remove '^/csam/' from exclude_patterns
    # - "^/csam/student-success-center/career-services/cooperative-education-and-internships/?$"

  path_blocklist:
    - "/search"
    - "\\?(utm_|fbclid=)"

  include_profilepages: false

# CHANGE (Incremental Update Logic):
# Centralized UA, rate-limit, and timeout used during fetching; works with conditional requests (ETag/Last-Modified).
# centralizes rate limit, timeout, user agent
crawl:
  rate_limit_seconds: 0.3
  timeout_seconds: 40
  user_agent: "MSU-FAQ-Bot/0.1 (contact: ramakrishnah1@montclair.edu)"

# Buckets (regex runs against URL PATH (not full URL), e.g., "/policies/academic-integrity/")
buckets:
  - name: soc
    include:
      - "^/school-of-computing/($|[^?]+)"
    exclude:
      - "^/school-of-computing/(19|20)\\d{2}/"                         # drop year archives
      - "^/school-of-computing/(author|category|tag)/"                 # drop taxanomies
      - "/page/\\d+/?$"                                                # drop pagination
      - "/amp/?$"                                                      # drop AMP

  - name: registrar
    include:
      - "^/red-hawk-central/registrar/($|[^?]+)"

  - name: policies
    # keep individual policy pages; drop some hubs, skip big hubs except detail pages under /all-policies/
    include:
      - "^/policies/(?!category/|responsible-office/|all-policies/?$)[^?]+$"
      - "^/policies/all-policies/[^/][^?]+$"     # allow detail pages under /all-policies/

  - name: student-services
    include:
      - "^/student-services/($|[^?]+)"
    exclude:
      - "^/student-services/(19|20)\\d{2}/"      # drop dated news posts
      - "/page/\\d+/?$"

  - name: oge
    include:
      - "^/global/($|[^?]+)"
    exclude:
      - "^/global/(19|20)\\d{2}/"                # drop dated news posts
      - "/page/\\d+/?$"
 
  # Graduate program details
  - name: grad-programs
    include:
      - "^/graduate/programs-of-study/(computer-science-ms|computer-science-combined-bsms|computational-linguistics-ms|cybersecurity-ms|data-science-ms|information-technology-ms|computing-technology-certificate)/?$"
      - "^/graduate/programs-of-study/(computer-science-ms|computer-science-combined-bsms|computational-linguistics-ms|cybersecurity-ms|data-science-ms|information-technology-ms|computing-technology-certificate|applied-mathematics-ms)/?$"


  # Combined programs (CS/IT/Data only)
  - name: combined-programs
    include:
      - "^/combined-programs/(programs-of-study/)?(computer-science-.*|information-technology-.*|data-science-.*)/?$"
      - "^/combined-programs/computer-science-combined-bs-ms/?$"   # the specific slug in your list

  # Red Hawk services (non-registrar)
  - name: red-hawk-services
    include:
      - "^/red-hawk-central/contact/?$"
      - "^/red-hawk-central/services/academic-advising/?$"
      - "^/red-hawk-central/waitlist-for-students/?$"
      - "^/red-hawk-central/financial-aid/.+?$"          # allow deep paths like .../sap-regulations/...

  # IT policies / service desk
  - name: it-policies
    include:
      - "^/information-technology/it-policies-and-procedures/[^/][^?]+/?$"
      - "^/information-technology/it-service-desk/?$"

  # Student Center
  - name: student-center
    include:
      - "^/student-center/(reservable-rooms|scheduling)/?$"

  # Policy PDFs
  - name: policies-pdf
    include:
      - "^/policies/wp-content/uploads/.*\\.pdf$"

  # University policy PDFs (older path)
  - name: university-policies-pdf
    include:
      - "^/university-policies/wp-content/uploads/.*\\.pdf$"

    # Red Hawk Central → Student Accounts (costs, deadlines, payment options)
  - name: rhc-student-accounts
    include:
      - "^/red-hawk-central/student-accounts/[^?]+$"

  # Graduate admissions "How to Apply" (and its subpages)
  - name: grad-how-to-apply
    include:
      - "^/graduate/how-to-apply(/[^?]+)?/?$"   # matches /graduate/how-to-apply and deeper pages

  # Site-wide uploads PDFs (covers HIPAA, fact sheets, etc. not under /policies/)
  - name: uploads-pdf
    include:
      - "^/wp-content/uploads/.*\\.pdf$"
  
  # discover catalogs
  - name: catalog
    include:
      - "^/programs/(computer-science|information-technology|data-science|applied-math[^/]*|applied-mathematics[^/]*|game-development[^/]*)/?$"
      - "^/courses/(cs|csit)[a-z0-9-]*/?$"
  
  # online programs
  - name: online-programs
    include:
      - "^/online/graduate-degrees/information-technology-ms-psm/?$"
  

# Further narrow down the 'policies' bucket to topics under current scope.
# URL allow-list for policies (lets in likely matches incl. synonyms)
policy_focus_allowlist:
  # direct slugs (keep)
  - "^/policies/all-policies/class-absence-documentation(/|$)"
  - "^/policies/all-policies/academic-integrity(/|$)"
  - "^/policies/all-policies/grading(/|$)"
  - "^/policies/all-policies/withdrawal(/|$)"
  - "^/policies/all-policies/leave-of-absence(/|$)"
  # under /policies/all-policies/ (new)
  - "^/policies/all-policies/academic-integrity(/|$)"
  - "^/policies/all-policies/grading(/|$)"
  - "^/policies/all-policies/withdrawal(/|$)"
  - "^/policies/all-policies/leave-of-absence(/|$)"
  # loose variants (optional, also add all-policies versions)
  - "^/policies/(all-policies/)?[^/]*integrity[^/]*/?$"
  - "^/policies/(all-policies/)?[^/]*misconduct[^/]*/?$"
  - "^/policies/(all-policies/)?[^/]*grading[^/]*/?$"
  - "^/policies/(all-policies/)?[^/]*withdraw[^/]*/?$"
  - "^/policies/(all-policies/)?[^/]*leave[^/]*/?$"
  - "^/policies/(all-policies/)?[^/]*loa[^/]*/?$"


# Topic lexicon for content check (post-filter)
# Lexicon used by policy_postfilter.py to keep only on-topic policy files.
policy_topic_lexicon:
  academic-integrity:
    any:
      - "academic integrity"
      - "plagiarism"
      - "cheating"
      - "misconduct"
      - "honor code"
    must_one_of: []
  grading:
    any:
      - "grading"
      - "grades"
      - "grade policy"
      - "pass/fail"
      - "incomplete"
    must_one_of: []
  withdrawal:
    any:
      - "withdraw"
      - "withdrawal"
      - "course withdrawal"
      - "drop"
      - "unenroll"
    must_one_of: []
  leave-of-absence:
    any:
      - "leave of absence"
      - "loa"
      - "medical leave"
      - "personal leave"
      - "leave request"
    must_one_of: []
  # NEW
  class-absence:
    any:
      - "class absence"
      - "absence documentation"
      - "doctor's note"
      - "excused absence"
      - "attendance"
      - "missed class"
    must_one_of: []



# Global skip rules (apply to ALL paths before bucketing)
# Use these to drop content you never want anywhere.
exclude_patterns:
  - "\\?(utm_|fbclid=)"                 # tracking query strings
  - "\\.(jpg|jpeg|png|gif|svg|webp)$"   # image files
  - "^//"                               # protocol-relative externals (//example.com)
  - "^/~"                               # personal homepages (/~username)
  - "/profilepages/"                    # legacy profile pages
  - "/author/|/category/|/tag/"         # taxonomy archives
  - "/\\d{4}/\\d{2}/"                   # date-based posts (/2025/09/)
  - "/events/\\d{4}/\\d{2}/"            # event archives
  - "/page/\\d+/?$"                     # pagination (/page/2/)
  - "/feed/$"                           # RSS endpoints
  - "/wp-json/"                         # REST root
  - "^/csam/"                           # College of Science & Math pages
  - "^/human-resources/"                # Human Resource pages
  - "^/pseg-sustainability-institute"   # out of scope
  - "^/newscenter/"                     # news articles (not FAQ content)


# filter out url's based on current scope
include_prefixes:
  - "/school-of-computing/"           # school of computing 
  - "/red-hawk-central/registrar/"    # registrar, add or drop, contact hours
  - "/global/"                        # office of global engagement
  - "/policies/"                      # policies & procedures
  - "/student-services/"              # important dates , details and deadlines


# Add manually if any pages or pdf does not appear in sitemap
manual:
  - "https://www.montclair.edu/university-policies/wp-content/uploads/sites/205/2018/08/Account-Management-Policy-1.0.pdf"
  - "https://www.montclair.edu/policies/wp-content/uploads/sites/205/2019/03/Procurement_Policies.pdf"


# File output locations
paths:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  url_list_csv: "data/url_list.csv"
