# Developer: Harshitha
# MSU FAQ Chatbot crawl config (SOC + Academics Programs + Registrar + Policies + Student Services + OGE)

site:
  base: 'https://www.montclair.edu'
  soc:  'https://www.montclair.edu/school-of-computing'

# ---- Seed sitemap indexes ----
sitemaps:
  - 'https://www.montclair.edu/wp-sitemap.xml'
  - 'https://www.montclair.edu/school-of-computing/wp-sitemap.xml'
  - 'https://www.montclair.edu/policies/wp-sitemap.xml'
  - 'https://www.montclair.edu/red-hawk-central/wp-sitemap.xml'
  - 'https://www.montclair.edu/student-services/wp-sitemap.xml'
  - 'https://www.montclair.edu/global/wp-sitemap.xml'
  - 'https://www.montclair.edu/graduate/wp-sitemap.xml'
  - 'https://www.montclair.edu/information-technology/wp-sitemap.xml'
  - 'https://www.montclair.edu/academics/wp-sitemap.xml'
  - 'http://catalog.montclair.edu/sitemap.xml'

# ---- Discovery ----
discovery:
  autositemap: true
  recheck_interval_days: 0         # set 0 for a clean re-fetch while testing anchors
  last_run_db: 'state/last_run.json'

  domain_whitelist:
    - 'montclair.edu'
    - 'www.montclair.edu'
    - 'catalog.montclair.edu'

  seed_pages:
    - 'https://www.montclair.edu/school-of-computing/graduate/'
    - 'https://www.montclair.edu/school-of-computing/undergraduate-students/'
    - 'https://www.montclair.edu/academics/programs/'
    - 'https://www.montclair.edu/academics/academic-calendar/'
    - 'http://catalog.montclair.edu/coursesaz/csit/'
    - 'http://catalog.montclair.edu/coursesaz/csam/'
    - 'http://catalog.montclair.edu/coursesaz/cmp-bc/'
    - 'http://catalog.montclair.edu/general-information/'
    - 'https://www.montclair.edu/policies/category/academic/'
    - 'https://www.montclair.edu/student-services/guide/'
    - 'https://www.montclair.edu/global/how-to-apply/graduate-students/'

  # Path rules (match on URL PATH only; fragments are not part of PATH)
  path_allowlist:
    # SOC hubs
    - '^/school-of-computing/($|[^?]+)'

    # Academics Programs: only programs we care about
    - '^/academics/programs/(bs-computer-science|bs-information-technology|bs-data-science|ms-information-technology|ms-cybersecurity|ms-computer-science|game-programming-certificate|computing-technology-certificate-online)/?$'
    - '^/academics/academic-calendar/[^?]*$'

    # Registrar + Student Services core
    - '^/red-hawk-central/registrar/($|[^?]+)'
    - '^/student-services/($|guide/[^?]*$)'
    - '^/chss/student-services/student-resources/[^?]*$'

    # Policies (including category pages we need)
    - '^/policies/($|all-policies/[^/]+/?$|category/academic/[^?]*$)'

    # OGE (Global) incl. grad, appointments, contact, J-1
    - '^/global/[^?]*$'

    # Catalog: courses + programs + general information
    - '^/coursesaz/(csit|csam|cmp-bc)/($|[^?]+)$'

    # Program pages
    - '^/programs/(computer-science-(bs|ms)|information-technology-bs|data-sciences-bs|data-science-ms|cybersecurity-ms|game-development-certificate)/?$'

    - '^/general-information/($|grading-standards/[^?]*$)'

    # Catalog degree requirements + transfer guidelines
    - '^/undergraduate-graduate-degree-requirements/($|[^?]*$)'

    - '^/red-hawk-central/financial-aid/[^?]*$'

  path_blocklist:
    - '/search'
    - '\\?(utm_|fbclid=|gclid=)'
    - '^/global/(news-and-announcements|events)/'
    - '^/school-of-computing/(author|category|tag)/'
    - '/page/\\d+/?$'
    - '/feed/$'
    - '/wp-json/'

  include_profilepages: false

# ---- Crawl defaults ----
crawl:
  rate_limit_seconds: 0.3
  timeout_seconds: 40
  user_agent: 'MSU-FAQ-Bot/0.1 (contact: ramakrishnah1@montclair.edu)'

# ---- Buckets ----
buckets:
  - name: soc
    include:
      - '^/school-of-computing/($|[^?]+)'
    exclude:
      - '^/school-of-computing/(19|20)\\d{2}/'
      - '/(author|category|tag)/'
      - '/page/\\d+/?$'
      - '/amp/?$'

  - name: academics-programs
    include:
      - '^/academics/programs/(bs-computer-science|bs-information-technology|bs-data-science|ms-information-technology|ms-cybersecurity|ms-computer-science|game-programming-certificate|computing-technology-certificate-online)/?$'
      - '^/academics/academic-calendar/[^?]*$'

  - name: registrar
    include:
      - '^/red-hawk-central/registrar/($|[^?]+)'
      - '^/red-hawk-central/financial-aid/[^?]*$'

  - name: policies
    include:
      - '^/policies/all-policies/[^/][^?]+/?$'
      - '^/policies/category/academic/[^?]*$'
      - '^/policies/(?!category/|responsible-office/|all-policies/?$)[^?]+$'

  - name: student-services
    include:
      - '^/student-services/guide/[^?]*$'
      - '^/chss/student-services/student-resources/[^?]*$'

  - name: oge
    include:
      - '^/global/[^?]*$'

  - name: catalog-courses
    include:
      - '^/coursesaz/(csit|csam|cmp-bc)/($|[^?]+)$'

  - name: catalog-programs
    include:
      - '^/programs/(computer-science-(bs|ms)|information-technology-bs|data-sciences-bs|data-science-ms|cybersecurity-ms|game-development-certificate)/?$'
      - '^/general-information/($|grading-standards/[^?]*$)'
      - '^/undergraduate-graduate-degree-requirements/($|[^?]*$)'

  - name: it-policies
    include:
      - '^/information-technology/it-policies-and-procedures/[^/][^?]+/?$'
      - '^/information-technology/it-service-desk/?$'

  - name: policies-pdf
    include:
      - '^/policies/wp-content/uploads/.*\\.pdf$'

  - name: uploads-pdf
    include:
      - '^/(?:[^/]+/)*wp-content/uploads/.*\.pdf$'

  - name: catalog-programs-pdf
    include:
      - '^/programs/[^/]+/[^/]+\.pdf$'

  # NEW: catalog-root-pdf for degree requirements PDF under /undergraduate-graduate-degree-requirements/
  - name: catalog-root-pdf
    include:
      - '^/undergraduate-graduate-degree-requirements/.*\.pdf$'

# ---- Focused policy allowlist (unchanged core topics) ----
policy_focus_allowlist:
  - '^/policies/all-policies/class-absence-documentation(/|$)'
  - '^/policies/all-policies/academic-integrity(/|$)'
  - '^/policies/all-policies/grading(/|$)'
  - '^/policies/all-policies/withdrawal(/|$)'
  - '^/policies/all-policies/leave-of-absence(/|$)'
  - '^/policies/(all-policies/)?[^/]*integrity[^/]*/?$'
  - '^/policies/(all-policies/)?[^/]*misconduct[^/]*/?$'
  - '^/policies/(all-policies/)?[^/]*grading[^/]*/?$'
  - '^/policies/(all-policies/)?[^/]*withdraw[^/]*/?$'
  - '^/policies/(all-policies/)?[^/]*leave[^/]*/?$'
  - '^/policies/(all-policies/)?[^/]*loa[^/]*/?$'
  - '^/policies/all-policies/code-of-conduct(/|$)'

# ---- Topic lexicon (unchanged) ----
policy_topic_lexicon:
  academic-integrity: { any: ['academic integrity','plagiarism','cheating','misconduct','honor code'], must_one_of: [] }
  grading:            { any: ['grading','grades','grade policy','pass/fail','incomplete'], must_one_of: [] }
  withdrawal:         { any: ['withdraw','withdrawal','course withdrawal','drop','unenroll'], must_one_of: [] }
  leave-of-absence:   { any: ['leave of absence','loa','medical leave','personal leave','leave request'], must_one_of: [] }
  class-absence:      { any: ['class absence','absence documentation','doctor''s note','excused absence','attendance','missed class'], must_one_of: [] }

# ---- Global excludes (do NOT exclude /category globally) ----
exclude_patterns:
  - '\\?(utm_|fbclid=|gclid=)'
  - '\\.(jpg|jpeg|png|gif|svg|webp)$'
  - '^//'
  - '^/~'
  - '/profilepages/'
  - '/author/|/tag/'
  - '/\\d{4}/\\d{2}/'
  - '/events/\\d{4}/\\d{2}/'
  - '/page/\\d+/?$'
  - '/feed/$'
  - '/wp-json/'
  - '^/human-resources/'
  - '^/pseg-sustainability-institute'
  - '^/newscenter/'

# ---- Prefix pre-filter ----
include_prefixes:
  - '/school-of-computing/'
  - '/academics/programs/'
  - '/academics/academic-calendar/'
  - '/red-hawk-central/registrar/'
  - '/global/'
  - '/policies/'
  - '/student-services/'
  - '/chss/student-services/'
  - '/coursesaz/'
  - '/programs/'
  - '/general-information/'
  - '/undergraduate-graduate-degree-requirements/'
  - '/red-hawk-central/financial-aid/'
  - '/graduate/'
  - '/graduate-students/'
  - '/combined-programs/'

# ---- Manual must-have pages (safety net) ----
manual:
  # Academics programs (UG + Grad + cert)
  - 'https://www.montclair.edu/academics/programs/bs-computer-science/'
  - 'https://www.montclair.edu/academics/programs/bs-information-technology/'
  - 'https://www.montclair.edu/academics/programs/bs-data-science/'
  - 'https://www.montclair.edu/academics/programs/ms-information-technology/'
  - 'https://www.montclair.edu/academics/programs/ms-cybersecurity/'
  - 'https://www.montclair.edu/academics/programs/ms-computer-science/'
  - 'https://www.montclair.edu/academics/programs/game-programming-certificate/'

  # Catalog programs + anchors (base URL is enough—sectionizer will create fragments)
  - 'http://catalog.montclair.edu/programs/computer-science-bs/'
  - 'http://catalog.montclair.edu/programs/data-sciences-bs/'
  - 'http://catalog.montclair.edu/programs/information-technology-bs/'
  - 'http://catalog.montclair.edu/programs/computer-science-ms/'
  - 'http://catalog.montclair.edu/programs/data-science-ms/'
  - 'http://catalog.montclair.edu/programs/cybersecurity-ms/'
  - 'http://catalog.montclair.edu/programs/game-development-certificate/'
  - 'http://catalog.montclair.edu/general-information/'
  - 'http://catalog.montclair.edu/general-information/grading-standards/'

  # Registrar + Academic calendar
  - 'https://www.montclair.edu/academics/academic-calendar/'
  - 'https://www.montclair.edu/red-hawk-central/registrar/'
  - 'https://www.montclair.edu/red-hawk-central/registrar/academic-regulations/'
  - 'https://www.montclair.edu/red-hawk-central/registrar/grades/'
  - 'https://www.montclair.edu/red-hawk-central/registrar/request-transcripts/'

  # Policies (category + core policies)
  - 'https://www.montclair.edu/policies/category/academic/'
  - 'https://www.montclair.edu/policies/all-policies/academic-integrity/'
  - 'https://www.montclair.edu/policies/all-policies/grading/'
  - 'https://www.montclair.edu/policies/all-policies/withdrawal/'
  - 'https://www.montclair.edu/policies/all-policies/leave-of-absence/'

  # Student resources
  - 'https://www.montclair.edu/student-services/guide/'
  - 'https://www.montclair.edu/chss/student-services/student-resources/'

  # OGE
  - 'https://www.montclair.edu/global/how-to-apply/graduate-students/'
  - 'https://www.montclair.edu/global/12-month-opt-reporting-requirements/'
  - 'https://www.montclair.edu/global/opt-reporting/'
  - 'https://www.montclair.edu/global/leave-of-absence/'
  - 'https://www.montclair.edu/global/h-1b-cap-gap-extension/'

  # SOC hubs
  - 'https://www.montclair.edu/school-of-computing/graduate/'
  - 'https://www.montclair.edu/school-of-computing/undergraduate-students/'
  - 'https://www.montclair.edu/school-of-computing/student-advising/'

  # Catalog degree requirements + transfer guidelines + financial aid
  - 'http://catalog.montclair.edu/undergraduate-graduate-degree-requirements/'
  - 'http://catalog.montclair.edu/undergraduate-graduate-degree-requirements/ug-transfer-guidelines/'
  - 'https://www.montclair.edu/red-hawk-central/financial-aid/'
  - 'https://www.montclair.edu/academics/programs/computing-technology-certificate-online/'

  # NEW: grad / combined pages
  - 'https://www.montclair.edu/graduate/stem/'
  - 'https://www.montclair.edu/combined-programs/faqs/'

  # NEW: key PDFs (degree requirements + grad policies)
  - 'http://catalog.montclair.edu/undergraduate-graduate-degree-requirements/undergraduate-graduate-degree-requirements.pdf'
  - 'https://www.montclair.edu/graduate-students/wp-content/uploads/sites/256/2024/09/Graduate-School-Policies-2024-2025-1.pdf'

  # NEW: catalog program PDFs (CS / DS / IT etc.)
  - 'http://catalog.montclair.edu/programs/computer-science-bs/computer-science-bs.pdf'
  - 'http://catalog.montclair.edu/programs/data-science-ms/data-science-ms.pdf'
  - 'http://catalog.montclair.edu/coursesaz/csit/csit.pdf'
  - 'http://catalog.montclair.edu/programs/computer-science-ms/computer-science-ms.pdf'
  - 'http://catalog.montclair.edu/programs/information-technology-bs/information-technology-bs.pdf'
  - 'http://catalog.montclair.edu/programs/computer-science-minor/computer-science-minor.pdf'
  - 'http://catalog.montclair.edu/programs/computer-science-combined-bs-ms-data-science/computer-science-combined-bs-ms-data-science.pdf'
  - 'http://catalog.montclair.edu/programs/information-technology-ms/information-technology-ms.pdf'

  # Policies: Code of Conduct (must-have)
  - 'https://www.montclair.edu/policies/all-policies/code-of-conduct/'

# ---- Rendering / table extraction ----
render_js_prefixes:
  - 'https://www.montclair.edu/red-hawk-central/registrar/'

table_extract_prefixes:
  - 'https://www.montclair.edu/red-hawk-central/registrar/'
  - 'https://www.montclair.edu/policies/all-policies/'
  - 'https://www.montclair.edu/policies/category/academic/'
  - 'https://www.montclair.edu/student-services/'
  - 'https://www.montclair.edu/global/'
  - 'https://www.montclair.edu/graduate/how-to-apply/'
  - 'https://www.montclair.edu/academics/academic-calendar/'
  - 'http://catalog.montclair.edu/programs/'
  - 'http://catalog.montclair.edu/general-information/'

table_extract_patterns:
  - '^https://www\\.montclair\\.edu/red-hawk-central/registrar/.*$'
  - '^https://www\\.montclair\\.edu/policies/all-policies/[^/]+/?$'
  - '^https://www\\.montclair\\.edu/policies/category/academic/.*$'
  - '^https://www\\.montclair\\.edu/student-services/.*$'
  - '^https://www\\.montclair\\.edu/global/.*$'
  - '^https://www\\.montclair\\.edu/graduate/how-to-apply/.*$'
  - '^https://www\\.montclair\\.edu/academics/academic-calendar/.*$'
  - '^http://catalog\\.montclair\\.edu/programs/.*$'
  - '^http://catalog\\.montclair\\.edu/general-information/.*$'

term_patterns:
  - '(Fall|Spring|Summer|Winter)\\s+20\\d{2}'
session_patterns:
  - '(Session\\s+[ABC])'
deadline_header_patterns:
  - 'last day to add'
  - 'last day to add/drop'
  - 'last day to withdraw'
  - 'final day to withdraw'
  - 'withdrawal period begins'
  - 'waitlist ends'

# ---- Retrieval weighting ----
query_intents:
  deadline: ['last day to withdraw','withdrawal deadline','final day to withdraw','wd deadline','academic calendar']
  policy:   ['pass/fail','what happens when i withdraw','considered a withdrawal','policy','leave of absence','withdrawal policy','academic integrity','grading standards']
  contact:  ['contact','who do i email','phone','how do i request','advising','tutoring','counseling']

bucket_weights:
  default: { registrar: 1.00, policies: 0.98, student-services: 0.95, soc: 0.95, oge: 0.97, catalog-courses: 0.96, catalog-programs: 0.98, academics-programs: 0.99 }
  deadline: { registrar: 1.10, policies: 0.95, student-services: 0.90, catalog-programs: 0.92 }
  policy:   { policies: 1.12, registrar: 0.98, catalog-programs: 0.95 }
  contact:  { student-services: 1.08, registrar: 1.02, policies: 0.96 }

rank_weights: { embed: 0.55, bm25: 0.25, bucket: 0.10, feats: 0.10 }
diversity: { max_per_url: 2 }

bm25_guardrail:
  deadline_keywords: ['last day','final day','deadline','withdraw','calendar']
  max_gate_loss: 0.15

# Only index these buckets for now
allowed_buckets:
  - soc
  - academics-programs
  - registrar
  - policies
  - student-services
  - oge
  - catalog-courses
  - catalog-programs
  - uploads-pdf
  - policies-pdf
  - it-policies
  - catalog-programs-pdf
  - catalog-root-pdf

# ---- Output paths ----
paths:
  raw_dir: 'data/raw'
  processed_dir: 'data/processed'
  url_list_csv: 'data/url_list.csv'
