# Created By: Harshitha
# Split the big CSIT course catalog markdown file into one markdown file per course (CSIT515.md, CSIT615.md, ...)

from __future__ import annotations

from pathlib import Path
import re
import frontmatter
import textwrap


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_ROOT = PROJECT_ROOT / "data" / "processed" / "coursesaz" / "csit"

INPUT_MD = DATA_ROOT / "index.md"
OUTPUT_MD = DATA_ROOT / "csit_courses_split.md"


# --- Helpers ---------------------------------------------------------------

def normalize_heading_line(line: str) -> str:
    """
    Take a heading line like:
        "**CSIT 515  Software Engineering  (3 credits)**  "
    and normalize it to:
        "CSIT 515 Software Engineering (3 credits)"

    This is ONLY used for pattern matching; we keep the original
    markdown for the body text.
    """
    s = line.strip()

    # Strip leading/trailing bold markers
    if s.startswith("**") and s.endswith("**"):
        s = s[2:-2].strip()

    # Convert non-breaking spaces to normal spaces
    s = s.replace("\u00A0", " ")

    # Collapse multiple spaces
    s = re.sub(r"\s+", " ", s)

    return s


COURSE_RX = re.compile(
    r"^CSIT\s+(\d{3})\s+(.+?)\s+\((\d+)\s+credits?\)$"
)


def split_csit_courses() -> None:
    if not INPUT_MD.exists():
        raise FileNotFoundError(f"Expected input file not found: {INPUT_MD}")

    post = frontmatter.load(INPUT_MD)
    body = post.content

    lines = body.splitlines()

    courses: list[dict] = []
    current: dict | None = None

    for line in lines:
        norm = normalize_heading_line(line)
        m = COURSE_RX.match(norm)

        if m:
            # Start of a new course
            if current is not None:
                courses.append(current)

            code = "CSIT"
            number = m.group(1)
            title = m.group(2)
            credits = m.group(3)

            current = {
                "code": code,
                "number": number,
                "title": title,
                "credits": credits,
                "heading_norm": f"{code} {number} {title} ({credits} credits)",
                "lines": [],           # body lines until next course
            }
        else:
            if current is not None:
                current["lines"].append(line)

    if current is not None:
        courses.append(current)

    if not courses:
        raise RuntimeError(
            f"No CSIT course headings found in {INPUT_MD}. "
            "Check that the file still contains lines like "
            "'**CSIT 515  Software Engineering  (3 credits)**'."
        )

    print(f"[split_csit_courses] Detected {len(courses)} CSIT courses")

    # --- Build new markdown body ------------------------------------------

    out_blocks: list[str] = []

    # Small note at top so humans know what this file is
    out_blocks.append(
        textwrap.dedent(
            """
            <!--
            AUTO-GENERATED by ingest/split_csit_courses.py

            This file restructures the CSIT catalog page into per-course
            sections with real markdown headings, so the RAG system can
            more reliably answer questions like "tell me about CSIT 515"
            without confusing it with CSIT 615.
            -->
            """
        ).strip()
    )

    for c in courses:
        heading = c["heading_norm"]
        body_lines = c["lines"]
        # Trim leading/trailing blank lines in the body
        while body_lines and not body_lines[0].strip():
            body_lines.pop(0)
        while body_lines and not body_lines[-1].strip():
            body_lines.pop()

        body_text = "\n".join(body_lines).rstrip()

        block = f"### {heading}\n\n{body_text}\n"
        out_blocks.append(block)

    new_body = "\n\n".join(out_blocks).rstrip() + "\n"

    # Copy front-matter but tweak tags/title a bit
    new_post = frontmatter.Post(
        content=new_body,
        **{
            **post.metadata,
            "bucket": post.metadata.get("bucket", "catalog-courses"),
            "tags": sorted(
                set(list(post.metadata.get("tags", [])) + ["catalog-courses-split"])
            ),
            "source_title": post.metadata.get("source_title", "") or
                           "CSIT Courses (split per course)",
        },
    )

    OUTPUT_MD.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_MD.open("wb") as f:
        frontmatter.dump(new_post, f)

    print(f"[split_csit_courses] Wrote split catalog to {OUTPUT_MD}")


if __name__ == "__main__":
    split_csit_courses()
